### ISSUE TITLE
How to support user-configured triggerCharacters / other initialization options?

### ISSUE THREAD

**Issue by pappasam** [openlawlibrary/pygls#112]
What is the best way to provide "user configuration" when developing a server using `pygls`? I'm currently developing https://github.com/pappasam/jedi-language-server and am having trouble with this.

As a simple example, I've provided the following trigger characters:

```python
@SERVER.feature(COMPLETION, trigger_characters=[".", "'", '"'])
def lsp_completion(server: LanguageServer, params: CompletionParams):
    """Returns completion items"""
```

That said, it's possible some users would prefer to use only a "." as a trigger character. I'd like to give those users the ability to change this feature setting in their `settings.json`. For example:

```json
    "jls": {
      "command": "jedi-language-server",
      "args": [],
      "filetypes": ["python"],
      "initializationOptions": {
        "triggerCharacters": ["."]
      }
    },
```

How do I:

1. effectively access this configuration option, and
2. dynamically configure my server's features with it?

Thanks in advance for your help!

**Comment by pappasam** [comment]
Figured it out. I've removed the options from the feature itself and added this initialization method. Feel free to close issue, or to keep it open if you want to add some documentation around this use case.

```python
@SERVER.feature(INITIALIZE)
async def lsp_initialize(server: LanguageServer, params: InitializeParams):
    """Initialize language server"""
    trigger_characters = getattr(
        params.initializationOptions, "triggerCharacters", [".", "'", '"']
    )
    completion_response = await server.register_capability_async(
        RegistrationParams(
            [
                Registration(
                    COMPLETION_ID,
                    COMPLETION,
                    {"triggerCharacters": trigger_characters},
                )
            ]
        )
    )
    if completion_response is not None:
        server.show_message(
            "Error happened during completions registration.",
            MessageType.Error,
        )
    else:
        server.show_message("success!")
```

**Comment by danixeee** [comment]
@pappasam I have modified json-example to include this use-case, take a look at [here](https://github.com/openlawlibrary/pygls/pull/113/files).

I couldn't find a way to unregister a feature that is registered during initialization, because I am not sure what is the "id" in that case. I suggest you to use `initializeD` method to register all features which options could be changed in the future, with some predefined "id". That way you will be able to unregister it, and register it again with different options. I hope I have covered this in the example, let me know if you need anything.

How to test:

1. run json-server
1. in .vscode/settings.json add `{ "jsonServer.triggerCharacters": [".", ",", ":"] }`
1. press F1 and run "Change completion trigger characters" command
1. test completions with new trigger chars

You would probably want to re-register it automatically on configuration changes, but for some reason [didChangeConfiguration](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#workspace_didChangeConfiguration) is not working on my end.. I will take a look when I have more time.

**Comment by pappasam** [comment]
@danixeee using your example as a starting point, I implemented basic and (I believe) extendable user configuration rooted at the name `jedi`. I use a couple additional data structures and helper functions to make the example you provided above easier to repeat across other LSP methods in the future. See here: https://github.com/pappasam/jedi-language-server/blob/master/jedi_language_server/server.py#L214

I haven't tried getting re-registration to work yet, but it's on the Roadmap.

If and when you have time, I'd always appreciate your thoughts on the design, whether you can think of any ways I can improve it, or whether it provides any inspiration on your end to make this process easier for other language server authors.
