### ISSUE TITLE
Stop once the exit notification is received

### ISSUE THREAD

**Issue by rwols** [openlawlibrary/pygls#118]
It's not always the case that this framework shuts down its process once the exit notification is received. In fact once the parent process (the editor) exits, it might get into a busy spin loop, eating up an entire core in my CPU.

I'm fixing killing subprocesses editor-side, but you might want to make sure your process exits anyway, for other editors.

**Comment by rwols** [comment]
I'd suggest just calling `exit(0 if shutdown_received else 1)`.

**Comment by danixeee** [comment]
When I start the server over TCP, I notice that client sends only `shutdown` request and not `exit` notification after it. That happens when I close VS Code window, but I am pretty sure that it was working before. I guess pygls needs to periodically check if client's process is still alive and exit otherwise (#130).
