### ISSUE TITLE
Exception has occurred: Error: Header must provide a Content-Length property.

### ISSUE THREAD

**Issue by EFFYLYX** [openlawlibrary/pygls#133]
`Exception has occurred: Error: Header must provide a Content-Length property.
t StreamMessageReader.onData (/Users/.../ls/node_modules/vscode-jsonrpc/lib/messageReader.js:163:27)
 at Socket.<anonymous> (/Users/.../ls/node_modules/vscode-jsonrpc/lib/messageReader.js:148:18)
 at Socket.emit (events.js:203:13)
 at addChunk (_stream_readable.js:295:12)
 at readableAddChunk (_stream_readable.js:276:11)
 at Socket.push (_stream_readable.js:210:10)
 at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)`

I don't know what caused the exception of vscode-jsonropc. Sometimes this exception happens. Sometimes not. When the exception happens, the client cannot continue to work. 

 It looks like that the server sent the data in a wrong format. When in the debug mode, I found that the header read from the client was {Object(textDocument=Object(uri,postion,context))Content-Length: 126', Content-Type: 'application/vscode-jsonrpc; charset=utf-8'}. It seems that there should be a ',' between the Object () and Content-Length. I don't know why this issue could happen. Could someone help me fix it?

**Comment by perrinjerome** [comment]
If vscode communicates with language server by  stdout/stdin (which is the default) then it's cricital than the server process does not output random things on stdout otherwise it gets mixed in json-rpc messages.

Does this happen with a language server you are writing ? You should check that you don't have left some debugging print statements, if I remember correctly it causes this kind of errors.

**Comment by danixeee** [comment]
I hope @perrinjerome helped you, please re-open if you still have the issue.
