### ISSUE TITLE
package lacks `__version__`, results installed as version 0.0.0

### ISSUE THREAD

**Issue by cinghiopinghio** [openlawlibrary/pygls#189]
Hi,

After commit b7601dd0d208602d07a80d9c6ab154f715d8f700, the metadata in `setup.cfg` lacks the version number resulting in `pygls` being installed (in Archlinux) as version `0.0.0` when checked with:
```python
from importlib.metadata import version
print(version('pygls'))
```
or the corresponding method with `pkg_resources`.
This causes conflicts with other packages requiring some `pygls` versions (e.g. [anakin-language-server](https://github.com/muffinmad/anakin-language-server)).

**Comment by danixeee** [comment]
You need to install all build [dependencies](https://github.com/openlawlibrary/pygls/blob/master/pyproject.toml#L2).

@KOLANICH Since you made this change, could you confirm?

**Comment by cinghiopinghio** [comment]
@danixeee : all those dependencies are well installed with the most recent version.

**Comment by cinghiopinghio** [comment]
In particular the installed versions are:
- `setuptools==56.0.0`
- `wheel==0.36.2`
- `setuptools_scm==5.0.2`

**Comment by danixeee** [comment]
@cinghiopinghio Did you try updating `setup.cfg` as I suggested?

**Comment by cinghiopinghio** [comment]
Ohh, this is weird.

I reproduced the steps used on the `PKGBUILD` to build the package in Archlinux and now I magically have the right version.

So to conclude: using any installation method (`pip` or `setup.py`, `local` or `global`, with or without your suggestions) it works.
It has to be something to do with the packaging process. I'll open an issue [there](https://github.com/archlinux/svntogit-community/tree/packages/python-pygls)

**Comment by danixeee** [comment]
I had the same issue because I forgot to install the `toml` extra dependency.

**Comment by eli-schwartz** [comment]
Moving the setuptools_scm stuff from pyproject.toml to setup.cfg seems like the correct choice.

pyproject.toml build-system.requires tells pep 517 how to select the setuptools build backend, but it is setuptools itself which needs to know that setuptools_scm[toml] is needed. So that requirement needs to be specified in a way that guarantees setuptools always knows about it, i.e. in the setuptools native format, which is not pyproject.toml but rather setup.cfg

As a result of this incorrect specification, you're allowed to run python setup.py and it won't yell at you about missing dependencies unless they produce e.g. ImportError.

@cinghiopinghio nothing is weird, this builds fine if and only if you by sheer coincidence had setuptools_scm/toml already installed

**Comment by polyzen** [comment]
The missing build deps were added to the Arch Linux package.

**Comment by KOLANICH** [comment]
I'm  sorry for the delay, I was offline.

>Moving the setuptools_scm stuff from pyproject.toml to setup.cfg seems like the correct choice.

Not quite. `setuptools_scm` doesn't support configuration in `setup.cfg` And it is good, because  the community has decided to promote `pyproject.toml` as a single config for all info related to package building (it may be possible to move the contents of `setup.cfg` there too).

 >So that requirement needs to be specified in a way that guarantees setuptools always knows about it, i.e. in the setuptools native format, which is not pyproject.toml but rather setup.cfg

Yeah. I have created a PR about it,  #191. Almost the same as @danixeee has proposed, but just mirrors the versions from `pyproject.toml` and on the single line

**Comment by KOLANICH** [comment]
>all those dependencies are well installed with the most recent version

@cinghiopinghio, please note that latest versions of `pip` and `setuptools` and `build` by default do such harmful thing as `build isolation`. During the build process it creates a some kind of virtualenv (not a real virtuaprnv) and installs there build deps from scratch. Fortunately, it can be disabled. For `pip` one can use a flag (and it can be even added into `pip.cfg`, but there is a nuance: it is a negative flag, so it must look like double negation currently (I have proposed a PR into pip fixing that some time ago, but it was rejected on the basis that it is a backward-incompatible change that should be done somewhen later) ). For `build` one has to add `-n` flag into CLI every time.

**Comment by eli-schwartz** [comment]
> Not quite. `setuptools_scm` doesn't support configuration in `setup.cfg`

Sorry, by "the setuptools_scm stuff" I was referring to "the requirements list" in build-system.requires.
