### ISSUE TITLE
pygls only understands the file URI scheme.

### ISSUE THREAD

**Issue by pyscripter** [openlawlibrary/pygls#209]
As per title.  More specifically it does not handle properly the untitled scheme used by VS-Code.   The URI for unsaved buffers in VS-Code is "untitled:buffername".  But this is not handled properly by pygls.

See the debug output below for an example:

```
DEBUG:pygls.protocol:Received b'Content-Length: 151\r\nContent-Type: application/json; charset=utf-8\r\n\r\n{"jsonrpc": "2.0", "method": "textDocument/didOpen", "params": {"textDocument":{"uri":"untitled:module1","languageId":"python","version":0,"text":""}}}
DEBUG:pygls.protocol:Received b'Content-Length: 160\r\nContent-Type: application/json; charset=utf-8\r\n\r\n{"jsonrpc": "2.0", "id": 6, "method": "textDocument/definition", "params": {"textDocument":{"uri":"untitled:module1"},"position":{"line":15,"character":6}}}
DEBUG:pygls.protocol:Request message received.
INFO:pygls.protocol:Sending data: {"jsonrpc": "2.0", "id": 6, "result": [{"uri": "file:///C:/Delphi/Progs32/Python/Pyscripter/module1", "range": {"start": {"line": 11, "character": 4}, "end": {"line": 11, "character": 8}}}]}
```

As you can see the URI was changed by pygls from "untitled:module1" to "file:///C:/Delphi/Progs32/Python/Pyscripter/module1"
The scheme was changed to file and current directory was prepended to the buffer name.

Finally other URI schemes like ssh or for example file://192.168.10.20/f$/MyDir/SubDir/text.doc  would face similar problems.

**Comment by tombh** [comment]
Sorry for the late reply! Over a year 😬

So if this is still an issue, I assume the source of it is in: https://github.com/openlawlibrary/pygls/blob/master/pygls/uris.py

Particularly this method:
```python
def to_fs_path(uri):
    """Returns the filesystem path of the given URI.

    Will handle UNC paths and normalize windows drive letters to lower-case.
    Also uses the platform specific path separator. Will *not* validate the
    path for invalid characters and semantics.
    Will *not* look at the scheme of this URI.
    """
    try:
        # scheme://netloc/path;parameters?query#fragment
        scheme, netloc, path, _params, _query, _fragment = urlparse(uri)

        if netloc and path and scheme == 'file':
            # unc path: file://shares/c$/far/boo
            value = f'//{netloc}{path}'

        elif RE_DRIVE_LETTER_PATH.match(path):
            # windows drive letter: file:///C:/far/boo
            value = path[1].lower() + path[2:]

        else:
            # Other path
            value = path

        if IS_WIN:
            value = value.replace('/', '\\')

        return value
    except TypeError:
        return None
```

I've written a failing test [here](https://github.com/openlawlibrary/pygls/commit/19033c94beb8ca37511d771cac6c0d064205dce0), does that encapsulate the issue do you think?

**Comment by pyscripter** [comment]
Thanks for getting back to me.
Yes the test looks good.   Unknown schemes should be left untouched.

**Comment by tombh** [comment]
Ok, I'll look into fixing this soon then.

**Comment by pyscripter** [comment]
Thank you.  Please also reopen my other issue #211.

**Comment by pyscripter** [comment]
https://github.com/openlawlibrary/pygls/commit/19033c94beb8ca37511d771cac6c0d064205dce0 never made it to the main branch, and after more than a year there is no progress...

**Comment by alcarney** [comment]
> after more than a year there is no progress in resolving this.

Apologies!  No idea how I missed this issue! :facepalm: 

I don't think `to_fs_path` is the whole story... while it does modify the untitled URI it doesn't change it as dramatically as the logs show in your original post.
```
>>> from pygls.uris import to_fs_path
>>> to_fs_path('untitled:module1')
'module1'
```
> I guess all it would take is:

If anything I'd argue we should have `to_fs_path` return `None` for URIs other than `file`. Since it only makes sense to call `to_fs_path` for `file` URIs this function should clearly indicate to the calling code that it should not be treating the URI as a regular file.

Are you able to share the code corresponding to `textDocument/definition` implementation from your original post? I am  unfortunately, unable to reproduce this issue using our example [goto.py](https://github.com/openlawlibrary/pygls/blob/b13b25223a7299cbfb7e61090d1656d82021de14/examples/servers/goto.py) server 

![image](https://github.com/openlawlibrary/pygls/assets/2675694/35234fb6-42cd-4d58-96c6-4b475618d810)

**Comment by pyscripter** [comment]
Thanks for getting back to me on this.

You are right this is not quite as simple.   The issue comes from the [jedi-language-server](https://github.com/pappasam/jedi-language-server), when it returns a location inside a file (e.g. go to definition).

If you are familiar with jedi, it defines a module using:

```python
def script(project: Optional[Project], document: Document) -> Script:
    """Simplifies getting jedi Script."""
    return Script(code=document.source, path=document.path, project=project)
```

The document path is converted by jedi to Path(document.path).absolute()

As you can see the document path is used and then in

```
def lsp_location(name: Name) -> Optional[Location]:
    """Get LSP location from Jedi definition."""
    module_path = name.module_path
    if module_path is None:
        return None

    lsp = lsp_range(name)
    if lsp is None: 
        return None

    return Location(uri=module_path.as_uri(), range=lsp)
```
and the as_uri() pathlib method is used giving rise to "file:///C:/Delphi/Progs32/Python/Pyscripter/module1" in the original example.

So it is mostly an issue with jedi and the jedi-language-server.  I agree on pygls side `to_fs_path` should probably return None for unknown schemes, but I guess this might break a lot of existing code.

You may close the issue or else reconsider how `to_fs_path` handles unknown schemes.

**Comment by marcelldls** [comment]
@alcarney I believe this may be causing an issue in the wasm context when a virtual filesystem in used in the browser. For example, when I use `vscode-test-web` to get a local browser vscode instance with my extension for development, the scheme is `vscode-test-web:`. With the workspace mounted to the wasm runtime, i would still like to use self.workspace.root_path/uri in order to resolve files relative to this and map it into wasm because I want to inspect the workspace - however I get `None`. Although I do have a workaround which is just to call `self.workspace.folders.keys()` which still gives the root_uri of the workspace

**Comment by alcarney** [comment]
> Although I do have a workaround which is just to call self.workspace.folders.keys() which still gives the root_uri of the workspace

I would say this is the preferred approach, as `root_path` and `root_uri` are deprecated in the [lsp specification](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#initializeParams)

```
/**
 * The rootPath of the workspace. Is null
 * if no folder is open.
 *
 * @deprecated in favour of `rootUri`.
 */
rootPath?: string | null;

/**
 * The rootUri of the workspace. Is null if no
 * folder is open. If both `rootPath` and `rootUri` are set
 * `rootUri` wins.
 *
 * @deprecated in favour of `workspaceFolders`
 */
rootUri: DocumentUri | null;
```

I expect this is because `root_uri` only really makes sense when you have a single folder mounted in the workspace. That said, assuming the client is setting `rootUri` in the `initialize` request I would expect it to be not `None` in pygls.

On the wasm front... I am surprised the server is seeing `vscode-test-web:` URIs, as there are [converters](https://github.com/alcarney/vscode-wasi-pygls/blob/b01af519f968ae3c5c9a1be83f8c2dbbeffd4cb6/src/common/client.ts#L181) that should be set which [map the uris](https://github.com/microsoft/vscode-wasm/blob/087363aadb1aeb18adaf91ef465fa530c1436681/wasm-wasi-lsp/src/main.ts#L152) to/from `file://` so (in theory at least!), the server should have no idea it's running in the browser.

**Comment by marcelldls** [comment]
@alcarney thank you for the feedback. Was unaware of the deprecation but it makes sense in order to generalise to multiroot workspaces.

Ah that's good to know - I was just using the default converters. I have actually been using my own implementation of the typescipt client as I'd like to also run off a host python interpreter for debugging the language server. Currently I just have the server check `os` and map the file paths to `/workspace` that way but that's probably just because I'm more familiar with python and was trying to get a demo together as a proof of concept - even if that is a bit dirty.

As far as wasm goes - we have found that the Gitlab web IDE does not seem to support it yet (didn't realise it would be that different from vscode.dev but hey ho). Even had to add the CORS headers with a proxy just to find that it won't let a wasm process be created anyways. So sadly our servers have no idea because they can't even run where we need them xD
