### ISSUE TITLE
`exclude_none = True` breaks `shutdown` requests 

### ISSUE THREAD

**Issue by alcarney** [openlawlibrary/pygls#245]
Unfortunately, it looks like #236 breaks [`shutdown`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#shutdown) requests.

I have a [command](https://github.com/swyddfa/esbonio/blob/ea8311a2b79ab8ef74157e9d5b2635e6b7b6a9e9/code/src/lsp/client.ts#L256) in Esbonio's VSCode extension that restarts the language server which sends a `shutdown` request to the server resulting in the following error

```
Command 'Esbonio: Restart Language Server' resulted in an error 
(The received response has neither a result or an error property.)
```

With VSCode's devtools open I can see the response received from the server and the `result` field is in fact missing.
```json
{
    "jsonrpc": "2.0",
    "id": 1
}
```
Changing `exclude_none` back to `exclude_unset` fixes this issue.

I'm not entirely sure what to suggest as a fix as while I didn't follow the discussion around #236 that closely I'm aware it was to resolve some other issues.

---
Edit: Actually it looks like this is an issue for any request where `"result": null` is a valid response which includes completions, goto definition and others

**Comment by dimbleby** [comment]
Aha.  I agree, `exclude_none` was an overshoot, because there are times when you do explicitly want to set a value to None.

In that case I think that we're going to want to come full circle and
- go back to using `exclude_unset=True` during serialization
- reinstate https://github.com/openlawlibrary/pygls/blob/f248002a2fb8a10fb9a5d2bd5a0160a04a6189aa/pygls/lsp/types/basic_structures.py#L57-L63

(where that latter bit of code says: if a field has a default that is not `None`, then act as if we set it explicitly.  This has the effect that not-`None` defaults are serialized even though `exclude_unset=True` is set)

@alcarney perhaps you'd like to submit an MR along those lines

**Comment by alcarney** [comment]
Sure I'll take a look :)
