### ISSUE TITLE
Message: TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by Maxattax97** [openlawlibrary/pygls#50]
I'd like to use this to build an LSP for a small language called OpenSCAD, so I started investigating this project (excellent code and docs by the way!). I'm normally a Neovim user, but for sake of better understanding pygls, I installed VS code (in other words, might just be a configuration error) and ran the example JSON language server in debug mode. Unfortunately, I'm quickly met with this error in the debug client running alongside the server:
```
[Error - 12:11:01 AM] Server initialization failed.
  Message: TypeError: 'NoneType' object is not iterable
  Code: -32602 
[object Object]
```

Any ideas on how I could get around this? Is this a new error, or is it a common bump in the road?

Thanks in advance.

**Comment by danixeee** [comment]
Hello @Maxattax97, I have cloned a fresh repo and tried to reproduce the error, but it is working fine on my end. I am using _pygls_ in another [project](https://github.com/textX/textX-LS) and I didn't notice the issue, as well.

Did you set the `python.pythonPath` in your `.vscode/settings.json`?

You can try to debug _pygls_, by setting a breakpoint [here](https://github.com/openlawlibrary/pygls/blob/master/pygls/protocol.py#L512). Since example is using _pygls_ from virtual environment, you have to open `protocol.py` file from location like `YOUR_VENV_PATH/site-packages/pygls/protocol.py`.

Thank you for your interests in this project, let me know if you have problems with debugging.

**Comment by dgreisen** [comment]
If we are able to figure out what is happening, perhaps we can provide a better error message than `'NoneType' object is not iterable` to smooth onboarding new developers.

**Comment by danixeee** [comment]
There are some predefined exceptions and all of them have following fields:

- code ( JSON RPC error codes from specification )
- message
- data ( should be a traceback )

```
interface ResponseError<D> {
	/**
	 * A number indicating the error type that occurred.
	 */
	code: number;

	/**
	 * A string providing a short description of the error.
	 */
	message: string;

	/**
	 * A Primitive or Structured value that contains additional
	 * information about the error. Can be omitted.
	 */
	data?: D;
}
```

but the `data` is displayed as `[object Object]` for some reason. I will see what I can do regarding that. There is also a log file which can be checked.
