### ISSUE TITLE
Using text_edit in a completion response breaks sort_text

### ISSUE THREAD

**Issue by OliverSchmitt** [openlawlibrary/pygls#75]
I tried to reproduce my problem with a simple example and modified the json-example from the repository in the following way:

```python
@json_server.feature(COMPLETION)
def completions(ls, params: CompletionParams = None):
    """Returns completion items."""
    line_index = params.position.line
    character_index = params.position.character
    to_insert = "Label"

    end = Position(line_index, character_index)
    text_edit = TextEdit(Range(end, end), to_insert)

    return CompletionList(True, [
        CompletionItem(
            label=to_insert,
            sort_text="1",
            # insert_text=to_insert,
            # text_edit=text_edit,
        ),
        CompletionItem(
            label="Laaa",
            sort_text="2",
        )
    ])
```

One would expect the *sort_text* property to overwrite the alphabetical order in which the completion items are shown. This is the case if the *insert_text* and *text_edit* are left commented out or just the *insert_text* property is used. If a completion is then triggered by typing "la" the expected completions are shown:

```
Label
Laaa
```

However, if *text_edit* is used with or without *insert_text* the provided sorting is ignored and the completion items are shown in alphabetical order:

```
Laaa
Label
```

I can not test this with another client to see is this problem only occurs with VS Code.

Another interesting thing that might be helpful is that VS Code does not highlight the prefix "la" in the completion item label when shown in the drop down menu if *text_edit* is used. This could be because the label is not the text to be inserted if a *text_edit* is provided. Maybe pygls or VS Code internally treat these cases differently and show the completion items with *text_edit* at the end of the drop down list.

**Comment by danixeee** [comment]
I have never tried that. It might be helpful to modify [this example](https://github.com/microsoft/vscode-extension-samples/tree/master/completions-sample) and let us know if it works with their language server SDK.

**Comment by OliverSchmitt** [comment]
I tried it with the completions sample and the following code in *src/extension.js*:
```javascript
provideCompletionItems(document: vscode.TextDocument, position: vscode.Position, token: vscode.CancellationToken, context: vscode.CompletionContext) {
	const to_insert = "Label";

	const labelCompletion = new vscode.CompletionItem(to_insert);
	labelCompletion.sortText = "1";
	// labelCompletion.insertText = to_insert;
	// labelCompletion.textEdit = new vscode.TextEdit(new vscode.Range(position, position), to_insert);

	const laaaaCompletion = new vscode.CompletionItem("Laaaa");
	laaaaCompletion.sortText = "2";

	// return all completion items as array
	return [
		laaaaCompletion,
		abelCompletion
	];
}
```
Testing the different cases I got the same results as with the pygls implementation. Nevertheless, the LSP specification does not mention any special behavior when using *text_edit* and *sort_text* and in my opinion using them simultaneously should not cause any problems.

It would still be helpful to see the behavior with another client to make sure this is not and issue only appearing with VS Code. I might be able to test this in the next view days.

One thing I forgot to mention is that the completion item order is according to *sort_text* if the completion is triggered with *ctrl+space*. This supports my  idea that completion items with *text_edit* are appended to the back of the list because the label is ignored and thus can not be used to filter for the prefix (in our case "la") that is already entered.

**Comment by danixeee** [comment]
Thank you for trying that out. 

> Nevertheless, the LSP specification does not mention any special behavior when using text_edit and sort_text and in my opinion using them simultaneously should not cause any problems.

I agree with this. It would be the best to ask on SO, or on LSP [github](https://github.com/Microsoft/vscode-languageserver-node) page.

There is a setting `editor.snippetSuggestions` which you can set when using snippet suggestions, but I am not sure if that solves your issue.

I will close this issue, since this is not a _pygls_ bug, but feel free to comment on this issue once you find out the solution.

**Comment by mike-vogel** [comment]
I copied the [above provideCompletionItems code](https://github.com/openlawlibrary/pygls/issues/75#issuecomment-507652251) for completion. When I type the completion character at the end of a line it works as expected. When I type the character in the middle of the line:
- The completion list appears at the end of the line rather than at the column in the line where I types the completion character
- Selecting a completion item replaces everything from the column where I typed the character to the end of the line

I've tried making the range bigger than the zero size in the above code but that doesn't change the behavior. It there a way to do completions in the middle of a line of text? 

From the spec I see InsertReplaceEdits which I don't see in the pygls types. Is using that what is needed to do a insert of a completion anywhere but the end?
