### ISSUE TITLE
Better typing support

### ISSUE THREAD

**Issue by perrinjerome** [openlawlibrary/pygls#93]
I have been using pygls, it's excellent, but I would love that we could use more of python typing features:
 * [ ] Make pygls itself type-check:
    * [x] Fix type errors reported by type checkers (maybe target only mypy) ( https://github.com/openlawlibrary/pygls/pull/92 is a start, but more is needed here )
    * [x] Run type checkers as part of automated test suite
 * [x] Have a bit more "stricts" type definitions (eg https://github.com/openlawlibrary/pygls/issues/88 )
 * [x] Includes a `py.typed` for https://www.python.org/dev/peps/pep-0561/ ( https://github.com/openlawlibrary/pygls/pull/91 )

If that's OK with you, I can send more pull requests for all this.

**Comment by danixeee** [comment]
@perrinjerome Thank you! I saw you made a few PRs, I will try to review them until the end of this week.

**Comment by danixeee** [comment]
@perrinjerome, @pappasam and I have also discussed adding a [runtime type-checking](https://github.com/openlawlibrary/pygls/issues/81) to make _pygls_ more robust.
What are your thoughts on that?
It should be an optional feature with [extra dependency](https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies) (if we decide to use a third party library) for those how want to enable it.

**Comment by bollwyvl** [comment]
Good ideas here!

I love me some pydantic, though another approach might be an typechecking/runtime checking implementation driven by a non-python spec. 

Since the LSP is JSON-native, JSON Schema, despite its warts, would be a good target. But _where would we get the schema?_ A while ago, I made some concrete strides towards building a JSON Schema for LSP, derived from the markdown spec and the reference nodejs implementation:

https://gist.github.com/bollwyvl/7a128978b8ae89ab02bbd5b84d07a4b7

it uses a mashup of python and node tools, and is hardly ready for prime-time, but shows significant promise.

With such a schema in-hand, rather than building into `pygls` proper, I would imagine such a package being standalone, e.g. `language-server-protocol` and versioned to releases of the LSP spec, with an extra digit for release churn, e.g. `3.14.x` which could have implementations generated for it, (e.g. https://quicktype.io). 

It could go one further, handling things like uri normalization (curse you, windows!), and use:
- a status quo validator (e.g. https://pypi.org/project/jsonschema)
- a performance-optimized one (e.g. https://github.com/horejsek/python-fastjsonschema) or 
- either on a best-effort basis

Similarly, for (de)serialization, it could use:
- stdlib `json`
- a performance-optimized one
  - https://pypi.org/project/ujson
  - https://pypi.org/project/orjson 
- best-effort import
for actually parsing things

This could then be tested robustly against that matrix, as well as multiple (future) versions of `pygls`, such that issues between upcoming, unreleased specs and `pylgs` could be found sooner.

`pygls` could then confidently depend on the above package, without having to release new versions tied too tightly to the protocol.

From a downstream perspective, a specific language server implementation could then choose the version of LSP it would support, and what dependency weight/performance tradeoff it would make on behalf of its users.

**Comment by danixeee** [comment]
@bollwyvl that is even a better idea! We should create a discussion issue and move these messages there.

**Comment by bollwyvl** [comment]
Yeah, the reference implementation of the protocol doesn't make for light reading, but if there is Truth, it's coming from there, forget whatever it says in the spec. Will open issue!

**Comment by perrinjerome** [comment]
I guess this can be closed now, this was originally about the static typing support.

There are still discussions using type information at runtime, but this is now discussed on https://github.com/openlawlibrary/pygls/issues/101 ( and maybe a bit on https://github.com/openlawlibrary/pygls/issues/81 ).
